### ISSUE TITLE
Wrong null format being passed to SPI_execute_with_args

### ISSUE THREAD

**Issue by derekjn** [pipelinedb/pipeline_kinesis#12]
Annoyingly, `SPI_execute_with_args` uses a non-Boolean format to represent nulls:
- `NULL`: `'n'`
- non-null: `' '`

See `pl_exec.c:PreparedParamsData.nulls`.

**Comment by usmanm** [comment]
Hahaha, yea I discovered that after banging my head against the wall for a bit. It's so stupid.
